/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.FlightEntry;
import bl.FlightType;
import db.DatabaseManagement;
import db.ScheduledFlightException;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author elisc
 */
public class EntryDialog extends javax.swing.JDialog {

    boolean success = false;
    FlightEntry entry = null;
    DatabaseManagement bl;

    public void initCbFlightType() {
        for (FlightType type : FlightType.values()) {
            cbFlightType.addItem(type);
        }
    }

    public boolean isSuccess() {
        return success;
    }

    public FlightEntry getEntry() {
        return entry;
    }

    /**
     * Creates new form EntryDialog
     */
    public EntryDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initCbFlightType();

        try {
            bl = DatabaseManagement.getInstance();
        } catch (Exception ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbFlightType = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txAirport = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txStartTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txFlightTime = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txMachineType = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txAirline = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txFlightCode = new javax.swing.JTextField();
        btOk = new javax.swing.JButton();
        btAbort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(7, 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Flight type");
        jPanel1.add(jLabel2);

        jPanel1.add(cbFlightType);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Airport");
        jPanel1.add(jLabel6);

        txAirport.setText("Singapore");
        jPanel1.add(txAirport);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Start time (hh:mm)");
        jPanel1.add(jLabel4);

        txStartTime.setText("16:00");
        jPanel1.add(txStartTime);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Flight time (hh:mm)");
        jPanel1.add(jLabel5);

        txFlightTime.setText("08:15");
        jPanel1.add(txFlightTime);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Machine type");
        jPanel1.add(jLabel1);

        txMachineType.setText("A380-800");
        jPanel1.add(txMachineType);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Airline");
        jPanel1.add(jLabel3);

        txAirline.setText("Quantas");
        jPanel1.add(txAirline);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Flight code");
        jPanel1.add(jLabel7);

        txFlightCode.setText("QFA1");
        jPanel1.add(txFlightCode);

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btAbort.setText("Abort");
        btAbort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btAbort, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btOk, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btAbort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        try {
            String airline = txAirline.getText();
            FlightType flighttype = (FlightType) cbFlightType.getSelectedItem();
            String airport = txAirport.getText();
            String machineType = txMachineType.getText();
            String flightCode = txFlightCode.getText();

            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm");
            LocalTime startTime = LocalTime.parse(txStartTime.getText(), dtf);
            LocalTime flightTime = LocalTime.parse(txFlightTime.getText(), dtf);

            if (bl.checkDbForEntry(flightCode)) {
                throw new ScheduledFlightException();
            }

            entry = new FlightEntry(flighttype, airport,
                    startTime, flightTime, machineType, airline, flightCode);
            
            success = true;
            this.dispose();
        } catch (ScheduledFlightException sf) {
            JOptionPane.showMessageDialog(null,
                    "Flight already scheduled!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    "Data has to be valid and complete!");
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void btAbortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbortActionPerformed
        success = false;
        this.dispose();
    }//GEN-LAST:event_btAbortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EntryDialog dialog = new EntryDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbort;
    private javax.swing.JButton btOk;
    private javax.swing.JComboBox<FlightType> cbFlightType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txAirline;
    private javax.swing.JTextField txAirport;
    private javax.swing.JTextField txFlightCode;
    private javax.swing.JTextField txFlightTime;
    private javax.swing.JTextField txMachineType;
    private javax.swing.JTextField txStartTime;
    // End of variables declaration//GEN-END:variables
}
