/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.DTFPattern;
import bl.FlightEntry;
import bl.FlightType;
import db.DatabaseManagement;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author elisc
 */
public class MainGUI extends javax.swing.JFrame implements DTFPattern{

    private DatabaseManagement bl;
    private TableModel model = new TableModel();

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        try {
            bl = DatabaseManagement.getInstance();
            if(bl.checkForExistingTable()){
                model.setEntries(bl.getData());
            }
            else{
                bl.createTableSchedule();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        tbMain.setModel(model);
        tbMain.setDefaultRenderer(Object.class, new TableRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbMain = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btAddEntry = new javax.swing.JMenuItem();
        btEditDelay = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btLoad = new javax.swing.JMenuItem();
        btSave = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbMain);

        jMenu1.setText("Edit");

        btAddEntry.setText("Add Schedule Entry");
        btAddEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddEntryActionPerformed(evt);
            }
        });
        jMenu1.add(btAddEntry);

        btEditDelay.setText("Edit Delay");
        btEditDelay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditDelayActionPerformed(evt);
            }
        });
        jMenu1.add(btEditDelay);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("File");

        btLoad.setText("Load");
        btLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoadActionPerformed(evt);
            }
        });
        jMenu2.add(btLoad);

        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        jMenu2.add(btSave);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddEntryActionPerformed
        EntryDialog dialog = new EntryDialog(this, true);

        dialog.setVisible(true);
        if (dialog.isSuccess()) {
            bl.addEntry(dialog.getEntry());
            model.add(dialog.getEntry());
        }
    }//GEN-LAST:event_btAddEntryActionPerformed

    private void btEditDelayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditDelayActionPerformed
        EditDialog dialog = new EditDialog(this, true);
        
        dialog.setVisible(true);
        if(dialog.isSuccess()){
            int selRow = tbMain.getSelectedRow();
            model.edit(selRow, dialog.getDelay());
            bl.editEntry(model.getEntry(selRow));
        }
    }//GEN-LAST:event_btEditDelayActionPerformed

    private void btLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoadActionPerformed
        try {         
            bl.createTableSchedule();
            model.setEntries(new ArrayList<FlightEntry>());
            
            BufferedReader br = new BufferedReader(new FileReader(new File("./schedule.csv")));
            
            String line = null;
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern(MAINPATTERN);
            
            while((line = br.readLine()) != null){
                String[] values = line.split(";");
                
                FlightEntry entry = new FlightEntry(
                    Enum.valueOf(FlightType.class, values[0]),
                    values[1],
                    LocalTime.parse(values[2], dtf),
                    LocalTime.parse(values[3], dtf),
                    values[6],
                    values[7],
                    values[8]
                );
                
                entry.setDelay(LocalTime.parse(values[4], dtf));
                
                bl.addEntry(entry);
                model.add(entry);
            }
        } catch (Exception ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btLoadActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        try {
            ArrayList<FlightEntry> entries = bl.getData();
            
            BufferedWriter bw = new BufferedWriter(new FileWriter(new File("./schedule.csv")));
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern(MAINPATTERN);
            
            for (FlightEntry entry : entries) {
                bw.write(entry.getType().toString());
                bw.write(";");
                bw.write(entry.getAirport());
                bw.write(";");
                bw.write(entry.getStartTime().format(dtf));
                bw.write(";");
                bw.write(entry.getFlightTime().format(dtf));
                bw.write(";");
                bw.write(entry.getDelay().format(dtf));
                bw.write(";");
                bw.write(entry.calcArrival().format(dtf));
                bw.write(";");
                bw.write(entry.getMachineType());
                bw.write(";");
                bw.write(entry.getAirline());
                bw.write(";");
                bw.write(entry.getFlightCode());
                bw.write("\n");
            }
            bw.flush();
        } catch (Exception ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btAddEntry;
    private javax.swing.JMenuItem btEditDelay;
    private javax.swing.JMenuItem btLoad;
    private javax.swing.JMenuItem btSave;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbMain;
    // End of variables declaration//GEN-END:variables
}
